### ISSUE TITLE
Incompatibility with new database files?

### ISSUE THREAD

**Issue by sergiophyceae** [richardmleggett/gi2tax#1]
Hello,

I have successfully used this script in the past to assign taxonomy to BLAST hits. However, I recently tried to update the taxonomy database and now acc2tax gives me an error. Is it possible that the new NCBI taxonomy databases have changed and acc2tax now has troubles with it?

Thank you,
--
acc2tax v0.4

Allocating memory for names list (2000000 entries)
Allocating memory for nodes list (2000000 entries)
Total memory required 30 Mb
Opening database file /scratch2/munoz/acc2tax/database_20180622//acc2tax_prot_all.txt
File size: 23029237460
Opening database file /scratch2/munoz/acc2tax/database_20180622//nodes.dmp
Opening database file /scratch2/munoz/acc2tax/database_20180622//names.dmp
Segmentation fault (core dumped)

**Comment by richardmleggett** [comment]
i think I've fixed this in the latest version, just updated now.
