### ISSUE TITLE
compilation problem?

### ISSUE THREAD

**Issue by DEsalasL** [richardmleggett/gi2tax#2]
Dear Richard,
I'm running into the problem below, would you please take a look at it? the compiler is gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

cc -o acc2tax acc2tax.c 
acc2tax.c: In function process_request_file:
acc2tax.c:498:25: warning: implicit declaration of function find_accession [-Wimplicit-function-declaration]
                 found = find_accession(query, buffer, &accession, &version, &taxid, &gi);
                         ^~~~~~~~~~~~~~

if I disregard the warning and try to use the program I get the error:
acc2tax -d database/ -i acc2taxIN -o testacc2tax.out
acc2tax v0.4
Allocating memory for names list (2000000 entries)
Allocating memory for nodes list (2000000 entries)
Total memory required 30 Mb
Opening database file database//acc2tax_nucl_all.txt
File size: 31668366645
Opening database file database//nodes.dmp
Opening database file database//names.dmp
Segmentation fault (core dumped)

Many thanks,
Dsalas

**Comment by richardmleggett** [comment]
i think I've fixed this in the latest version, just updated now.

**Comment by DEsalasL** [comment]
Many thanks. It is perfectly working now.
