### ISSUE TITLE
get taxid instead of taxonomy strings

### ISSUE THREAD

**Issue by meixilin** [richardmleggett/gi2tax#3]
Hi, 

Thank you for the amazing script! Is there an option to output the taxid directly instead of output the taxonomy string?, For example, the current output is this: 

`AC124319	cellular organisms,Eukaryota,Opisthokonta,Metazoa,Eumetazoa,Bilateria,Deuterostomia,Chordata,Craniata,Vertebrata,Gnathostomata,Teleostomi,Euteleostomi,Sarcopterygii,Dipnotetrapodomorpha,Tetrapoda,Amniota,Mammalia,Theria,Eutheria,Boreoeutheria,Euarchontoglires,Primates,Haplorrhini,Simiiformes,Catarrhini,Hominoidea,Hominidae,Homininae,Homo,Homo sapiens`

Is it possible to have an option to generate an output like this: 

`AC124319      9606`

Thank you so much!

**Comment by richardmleggett** [comment]
Hi,

**Comment by richardmleggett** [comment]
Hi, this is a good idea. I'll try and add it when I next get around to updating the code.
